# Generated by Django 3.1.4 on 2020-12-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygenerator', '0002_auto_20201214_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.CharField(max_length=44, unique=True),
        ),
    ]
