#include <wireguard.h>
from ipaddress import IPv4Network, IPv4Address

WG_INTERFACE_NAME = WIREGUARD_INTERFACE_NAME

TUNNEL_NETWORK = IPv4Network(WIREGUARD_IPV4NETWORK)

SERVER_TUNNEL_ADDRESS = IPv4Address(WIREGUARD_INTERFACE_ADDRESS)

// Define a pool
CLIENT_POOL_FIRST = IPv4Address(WIREGUARD_POOL_FIRST)
CLIENT_POOL_LAST = IPv4Address(WIREGUARD_POOL_LAST)

#ifndef WIREGUARD_ENABLED
WG_ENABLED = True
#else
WG_ENABLED = WIREGUARD_ENABLED
#endif
