#include <wireguard.h>
from ipaddress import IPv4Network

TUNNEL_NETWORK = IPv4Network(WIREGUARD_IPV4NETWORK)

SERVER_TUNNEL_ADDRESS = WIREGUARD_INTERFACE_ADDRESS

// Define a pool
CLIENT_POOL_FIRST = WIREGUARD_POOL_FIRST
CLIENT_POOL_LAST = WIREGUARD_POOL_LAST
