name : Pylava

on:
    push:
        paths:
            - '**.py'
            - '!*/migrations/**.py'



jobs:
    pylava:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Install pylava
              run: pip3 install pylava
            - name: Check code
              run: python3 -m pylava
