name : Unittest

on:
    push:
        paths:
            - '**.py'
            - '!*/migrations/**.py'



jobs:
    unittest_and_coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@master
            - name: Setup Test Configuration
              run: make CONFIGURATION_HEADERS=test config
            - name: Install python-ldap requirements
              run: sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev
            - name: Install required packages
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: install --dev
            - name: Run tests with coverage analysis
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: run coverage run manage.py test
            - name: Produce coverage report
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: run coverage xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./coverage.xml
                  flags: unittests
                  verbose: true
